### ISSUE TITLE
Ram size largest available part.

### ISSUE THREAD

**Issue by cb88** [tomverbeure/panologic#1]
8Mx32 is 32MByte not 64.

Wonder how hard it would be to swap the 256Mbit part for a 2Gbit one heat gun the old one off... flux then heat gun the new one on? Never done a BGA myself... but might be worth a try.

Note this may not physically fit... looks like it's wider. That resistor pack may be in the way.
https://www.avnet.com/shop/us/products/micron/mt46h64m32lfbq-48-wt-c-3074457345626233877?CMP=EMA_Octopart_inventoryfeed_VSE

**Comment by tomverbeure** [comment]
I've fixed the typo. 👍 

According to the datasheets of the 2 devices, the 256Mbit and the 2Gbit part both have a size of 8x13mm. The avnet site probably uses a picture of some generic memory chip? (The number of balls are matching though...)

I've only used a heat gun to destroy PCBs, not to replace stuff, but somebody with some experience should be able to make it work.

I just discovered that the Xilinx memory interface generator for Spartan-3E only supports DDR and not LPDDR.

So to make this work, a custom controller will be needed. I've gathered a bunch of relevant and less relevant resources [here](https://github.com/tomverbeure/panologic/blob/master/DDR.md).

The fastest way to get this going is probably to run it at considerably lower speed than the maximum possible 166MHz. LPDDR doesn't have a minimum clock speed requirement (because there's no DLL inside the DRAM itself). So I'll probably first run this at 50MHz or so initially.

Tom
